version: '3'  # Version of the Docker Compose syntax being used

services:
  web:  # Service name
    build: .  # Build context for the Docker image (current directory)
    command: node ./swagger.js # Command to start your FastAPI app
    ports:
      - 3000:3000  # Port mapping (host:container)
